name: Windows Build and Deploy

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test GUI imports
      run: |
        python -c "import tkinter; print('tkinter available')"
        python -c "import sqlite3; print('sqlite3 available')"
        python -c "import selenium; print('selenium available')"

    - name: Run basic functionality tests
      run: |
        python -c "import create_database; print('Database module imports successfully')"
        python -c "import gui_main; print('GUI module imports successfully')"

    - name: Build standalone executables
      run: |
        # Build GUI application as standalone executable
        pyinstaller --onefile --windowed --name "RnB-Snow-GUI" gui_main.py

        # Build console version for automation
        pyinstaller --onefile --name "RnB-Snow-Console" create_database.py

        # Build Selenium session tool
        pyinstaller --onefile --name "RnB-Snow-Selenium" selenium_debug_session.py

        # Create distribution directory
        mkdir dist-final
        copy dist\*.exe dist-final\
        copy README.md dist-final\
        copy *.csv dist-final\ 2>nul || echo "No CSV files to copy"

        # Create usage instructions
        echo "RnB Snow Ticket Matching System - Standalone Executables" > dist-final\USAGE.txt
        echo. >> dist-final\USAGE.txt
        echo "Files included:" >> dist-final\USAGE.txt
        echo "- RnB-Snow-GUI.exe: Main graphical interface" >> dist-final\USAGE.txt
        echo "- RnB-Snow-Console.exe: Command-line database operations" >> dist-final\USAGE.txt
        echo "- RnB-Snow-Selenium.exe: Web automation for email extraction" >> dist-final\USAGE.txt
        echo. >> dist-final\USAGE.txt
        echo "No Python installation required!" >> dist-final\USAGE.txt

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rnb-snow-windows-executables
        path: dist-final/

    - name: Push to private repository
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      env:
        PRIVATE_REPO_TOKEN: ${{ secrets.PRIVATE_REPO_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

        # Clone the private repository
        git clone https://${{ secrets.PRIVATE_REPO_TOKEN }}@github.com/makromaster/rnb-snow-builds.git private-repo

        # Copy files to private repo
        xcopy dist-final private-repo\ /E /Y

        # Commit and push to private repo
        cd private-repo
        git add .
        git commit -m "Automated build from main branch - $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')" || echo "No changes to commit"
        git push origin main